import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np

# --- PAGE SETUP ---
st.set_page_config(page_title="Aivena Workforce AI | Baseline Diagnostic", layout="wide")
st.title("📊 Workforce AI: 48-Hour Baseline Diagnostic")
st.markdown("This dashboard identifies current labor waste and service gaps under the traditional 48-hour scheduling model.")

# --- LOAD DATA ---
@st.cache_data
def load_all_data():
    try:
        # Load Raw Inputs
        df_stores = pd.read_csv('data/input/stores.csv')
        df_schedule = pd.read_csv('data/input/current_schedule.csv')
        
        # Load Diagnostic Outputs (Generated by calculate_detailed_kpis.py)
        df_store_diagnostics = pd.read_csv('data/output/store_level_diagnostics.csv')
        df_emp_diagnostics = pd.read_csv('data/output/employee_level_diagnostics.csv')
        
        # Merge schedule with store info for basic charts
        df_schedule = df_schedule.merge(df_stores[['store_id', 'format', 'city']], on='store_id')
        
        return df_schedule, df_store_diagnostics, df_emp_diagnostics
    except FileNotFoundError:
        st.error("Data not found. Please ensure both 'generate_synthetic_data.py' and 'calculate_detailed_kpis.py' have been run.")
        return None, None, None

df_schedule, store_master, emp_ledger = load_all_data()

if df_schedule is not None:
    # --- TOP LEVEL METRICS ---
    total_cost = df_schedule['labor_cost_mxn'].sum()
    target_cost = total_cost * 0.92
    
    col1, col2, col3 = st.columns(3)
    col1.metric("Current Total Labor Cost (MXN)", f"${total_cost:,.2f}")
    col2.metric("Target Cost to Win Challenge (-8%)", f"${target_cost:,.2f}")
    
    # Calculate Overtime Employees from the ledger
    ot_workers = len(emp_ledger[emp_ledger['overtime_hours'] > 0])
    col3.metric("Employees on 200% Overtime", f"{ot_workers} / {len(emp_ledger)}")

    st.divider()

    # --- CHARTS ROW 1 ---
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("1. Labor Cost by Store Format")
        cost_by_format = df_schedule.groupby('format')['labor_cost_mxn'].sum().reset_index()
        fig_format = px.pie(cost_by_format, values='labor_cost_mxn', names='format', 
                            hole=0.4, color_discrete_sequence=px.colors.sequential.Teal)
        st.plotly_chart(fig_format, width="stretch")

    with col_b:
        st.subheader("2. Overtime Leakage by Role")
        ot_by_role = emp_ledger[emp_ledger['overtime_hours'] > 0].groupby('role')['employee_id'].count().reset_index(name='Overtime Count')
        fig_role = px.bar(ot_by_role, x='role', y='Overtime Count', 
                          color='Overtime Count', color_continuous_scale='Reds')
        # FIXED: Changed 'fig' to 'fig_role' and updated width syntax
        st.plotly_chart(fig_role, width="stretch")

    st.divider()

    # --- DETAILED STORE PERFORMANCE TABLE ---
    st.subheader("3. Store-Level Operational Diagnostic")
    st.markdown("A deep dive into utilization vs. service effectiveness per store.")

    # Mapping CSV columns to Display Names
    display_cols = {
        'store_id': 'Store_ID',
        'city': 'City',
        'format': 'Format',
        'total_labor_cost': 'Total_Labor_Cost_MXN',
        'total_scheduled_hours': 'Capacity_Scheduled_Hours',
        'total_required_hours': 'Demand_Required_Hours',
        'labor_utilization_pct': 'Labor_Utilization_%',
        'service_level_pct': 'Service_Level_%',
        'waste_overstaffed_hours': 'Waste_Overstaffed_Hours',
        'total_understaffed_hours': 'Service_Gap_Understaffed_Hours'
    }

    # Select and rename for the dashboard
    df_table = store_master[list(display_cols.keys())].rename(columns=display_cols)

    # FIXED: Updated use_container_width to width="stretch"
    st.dataframe(
        df_table.style.format({
            'Total_Labor_Cost_MXN': '${:,.2f}',
            'Capacity_Scheduled_Hours': '{:,.0f}',
            'Demand_Required_Hours': '{:,.0f}',
            'Labor_Utilization_%': '{:.1f}%',
            'Service_Level_%': '{:.1f}%',
            'Waste_Overstaffed_Hours': '{:,.0f}',
            'Service_Gap_Understaffed_Hours': '{:,.0f}'
        }).background_gradient(subset=['Total_Labor_Cost_MXN', 'Waste_Overstaffed_Hours'], cmap='Reds')
          .background_gradient(subset=['Labor_Utilization_%', 'Service_Level_%'], cmap='RdYlGn'),
        width="stretch",
        height=500
    )

    with st.expander("👤 View Detailed Employee Ledger"):
        st.dataframe(
            emp_ledger.style.format({'total_labor_cost_mxn': '${:,.2f}'}), 
            width="stretch"
        )
        